PORT_OFFSET="${1:-0}"

echo "Initializing Horreum Application"

KEYCLOAK_PORT=$((8180 + PORT_OFFSET))
HORREUM_PORT=$((8080 + PORT_OFFSET))
POSTGRES_PORT=$((5432 + PORT_OFFSET))

if [ "$CONTAINER_RUNTIME" = "podman" ]; then
  IP_ADDR="127.0.0.1"
else
  IP_ADDR="172.17.0.1"
fi

JDBC_URL="jdbc:postgresql://$IP_ADDR:$POSTGRES_PORT/horreum"
echo "# Env generated by app-init.sh" > /cwd/horreum-backend/.env
echo "QUARKUS_DATASOURCE_JDBC_URL=$JDBC_URL" >> /cwd/horreum-backend/.env
echo "QUARKUS_DATASOURCE_MIGRATION_JDBC_URL=$JDBC_URL" >> /cwd/horreum-backend/.env
echo "QUARKUS_OIDC_AUTH_SERVER_URL=http://$IP_ADDR:$KEYCLOAK_PORT/auth/realms/horreum" >> /cwd/horreum-backend/.env
KEYCLOAK_HOST="$IP_ADDR:$KEYCLOAK_PORT"
HORREUM_URL="http://$IP_ADDR:$HORREUM_PORT"


while ! curl -s --fail $KEYCLOAK_HOST; do
  echo 'Waiting for Keycloak to start.'
  sleep 5;
done
KEYCLOAK_ADMIN_TOKEN=$(curl -s $KEYCLOAK_HOST/auth/realms/master/protocol/openid-connect/token -X POST -H 'content-type: application/x-www-form-urlencoded' -d 'username=admin&password=secret&grant_type=password&client_id=admin-cli' | jq -r .access_token)
[ -n "$KEYCLOAK_ADMIN_TOKEN" -a "$KEYCLOAK_ADMIN_TOKEN" != "null" ] || exit 1
AUTH='Authorization: Bearer '$KEYCLOAK_ADMIN_TOKEN
KEYCLOAK_BASEURL=$KEYCLOAK_HOST/auth/admin/realms/horreum

# Obtain client secrets for both Horreum and Grafana
HORREUM_CLIENTID=$(curl -s $KEYCLOAK_BASEURL/clients -H "$AUTH" | jq -r '.[] | select(.clientId=="horreum") | .id')
HORREUM_CLIENTSECRET=$(curl -s $KEYCLOAK_BASEURL/clients/$HORREUM_CLIENTID/client-secret -X POST -H "$AUTH" | jq -r '.value')
[ -n "$HORREUM_CLIENTSECRET" -a "$HORREUM_CLIENTSECRET" != "null" ] || exit 1
echo QUARKUS_OIDC_CREDENTIALS_SECRET=$HORREUM_CLIENTSECRET >> /cwd/horreum-backend/.env
chmod a+w /cwd/horreum-backend/.env
GRAFANA_CLIENTID=$(curl -s $KEYCLOAK_BASEURL/clients -H "$AUTH" | jq -r '.[] | select(.clientId=="grafana") | .id')
GRAFANA_CLIENTSECRET=$(curl -s $KEYCLOAK_BASEURL/clients/$GRAFANA_CLIENTID/client-secret -X POST -H "$AUTH" | jq -r '.value')
[ -n "$GRAFANA_CLIENTSECRET" -a "$GRAFANA_CLIENTSECRET" != "null" ] || exit 1
echo GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=$GRAFANA_CLIENTSECRET > /cwd/.grafana
chmod a+w /cwd/.grafana

# Create roles and example user in Keycloak
UPLOADER_ID=$(curl -s $KEYCLOAK_BASEURL/roles/uploader -H "$AUTH"  | jq -r '.id')
TESTER_ID=$(curl -s $KEYCLOAK_BASEURL/roles/tester -H "$AUTH" | jq -r '.id')
VIEWER_ID=$(curl -s $KEYCLOAK_BASEURL/roles/viewer -H "$AUTH" | jq -r '.id')
ADMIN_ID=$(curl -s $KEYCLOAK_BASEURL/roles/admin -H "$AUTH" | jq -r '.id')
curl -s $KEYCLOAK_BASEURL/roles -H "$AUTH" -H 'content-type: application/json' -X POST -d '{"name":"dev-team"}'
TEAM_ID=$(curl -s $KEYCLOAK_BASEURL/roles/dev-team -H "$AUTH" | jq -r '.id')
curl -s $KEYCLOAK_BASEURL/roles -H "$AUTH" -H 'content-type: application/json' -X POST -d '{"name":"dev-uploader","composite":true}'
TEAM_UPLOADER_ID=$(curl -s $KEYCLOAK_BASEURL/roles/dev-uploader -H "$AUTH" | jq -r '.id')
curl -s $KEYCLOAK_BASEURL/roles/dev-uploader/composites -H "$AUTH" -H 'content-type: application/json' -X POST -d '[{"id":"'$TEAM_ID'"},{"id":"'$UPLOADER_ID'"}]'
curl -s $KEYCLOAK_BASEURL/roles -H "$AUTH" -H 'content-type: application/json' -X POST -d '{"name":"dev-tester","composite":true}'
TEAM_TESTER_ID=$(curl -s $KEYCLOAK_BASEURL/roles/dev-tester -H "$AUTH" | jq -r '.id')
curl -s $KEYCLOAK_BASEURL/roles/dev-tester/composites -H "$AUTH" -H 'content-type: application/json' -X POST -d '[{"id":"'$TEAM_ID'"},{"id":"'$TESTER_ID'"},{"id":"'$VIEWER_ID'"}]'
curl -s $KEYCLOAK_BASEURL/users -H "$AUTH" -X POST -d '{"username":"user","enabled":true,"firstName":"Dummy","lastName":"User","credentials":[{"type":"password","value":"secret"}],"email":"user@example.com"}' -H 'content-type: application/json'
USER_ID=$(curl -s $KEYCLOAK_BASEURL/users -H "$AUTH" | jq -r '.[] | select(.username=="user") | .id')
curl -s $KEYCLOAK_BASEURL/users/$USER_ID/role-mappings/realm -H "$AUTH" -H 'content-type: application/json' -X POST -d '[{"id":"'$TEAM_UPLOADER_ID'","name":"dev-uploader"},{"id":"'$TEAM_TESTER_ID'","name":"dev-tester"},{"id":"'$ADMIN_ID'","name":"admin"}]'

# Create user that can list other users and roles
curl -s $KEYCLOAK_BASEURL/users -H "$AUTH" -X POST -d '{"username":"__user_reader","enabled":true,"credentials":[{"type":"password","value":"secret"}],"email":"none@example.com"}' -H 'content-type: application/json'
USER_READER_ID=$(curl -s $KEYCLOAK_BASEURL/users -H "$AUTH" | jq -r '.[] | select(.username=="__user_reader").id')
REALM_MANAGEMENT_CLIENTID=$(curl -s $KEYCLOAK_BASEURL/clients -H "$AUTH" | jq -r '.[] | select(.clientId=="realm-management").id')
VIEW_USERS_ID=$(curl -s $KEYCLOAK_BASEURL/clients/${REALM_MANAGEMENT_CLIENTID}/roles/view-users -H "$AUTH" | jq -r '.id')
curl -s $KEYCLOAK_BASEURL/users/$USER_READER_ID/role-mappings/clients/${REALM_MANAGEMENT_CLIENTID} -H "$AUTH" -H 'content-type: application/json' -X POST -d '[{"id":"'$VIEW_USERS_ID'","name":"view-users"}]'
USER_READER_TOKEN=$(curl -s -X POST $KEYCLOAK_BASEURL/protocol/openid-connect/token \
    -H 'content-type: application/x-www-form-urlencoded' \
    -d 'username=__user_reader&password=secret&grant_type=password&client_id=horreum-ui&scope=offline_access' \
    | jq -r .refresh_token)
echo HORREUM_KEYCLOAK_USER_READER_TOKEN=$USER_READER_TOKEN >> /cwd/horreum-backend/.env

echo "Horreum initialization complete"
