version: '3.1'
volumes:
  horreum_pg12: {}
  horreum_grafana: {}
services:
  postgres:
    image: docker.io/postgres:12
    environment:
    - POSTGRES_DB=horreum
    - POSTGRES_USER=dbadmin
    - POSTGRES_PASSWORD=secret
    ports:
    - 5432:5432
    volumes:
    - horreum_pg12:/var/lib/postgresql/data
  db-init:
    depends_on:
    - postgres
    image: docker.io/postgres:12
    restart: on-failure
    environment:
    - PGHOST=postgres
    - PGPORT=5432
    - PGDATABASE=horreum
    - PGUSER=dbadmin
    - PGPASSWORD=secret
    command:
    - bash
    - -x
    - -c
    - |
      psql -c "SELECT 1;" || exit 1
      if ! psql -t -c "SELECT 1 FROM pg_roles WHERE rolname = 'keycloak';" | grep -q 1; then
        psql -c "CREATE ROLE keycloak noinherit login password 'secret';"
      fi
      if ! psql -t -c "SELECT 1 FROM pg_database WHERE datname = 'keycloak';" | grep -q 1; then
        psql -c "CREATE DATABASE keycloak WITH OWNER = 'keycloak';"
      fi
      if ! psql -t -c "SELECT 1 FROM pg_roles WHERE rolname = 'appuser';" | grep -q 1; then
          psql -c "CREATE ROLE appuser noinherit login password 'secret';"
      fi
  keycloak:
    depends_on:
    - postgres
    image: docker.io/jboss/keycloak:latest
    command:
    - -Dkeycloak.profile.feature.upload_scripts=enabled
    - -Dkeycloak.migration.action=import
    - -Dkeycloak.migration.provider=singleFile
    - -Dkeycloak.migration.file=/etc/keycloak/imports/keycloak-horreum.json
    - -Dkeycloak.migration.strategy=IGNORE_EXISTING
    - -Djboss.socket.binding.port-offset=100
    - -Djboss.bind.address=127.0.0.1
    - -Djboss.bind.address.private=127.0.0.1
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=secret
    - DB_VENDOR=postgres
    - DB_ADDR=postgres
    - DB_PORT=5432
    - DB_DATABASE=keycloak
    - DB_USER=keycloak
    - DB_PASSWORD=secret
    ports:
    - 8180:8180
    volumes:
    - ./src/main/resources:/etc/keycloak/imports:ro,z
  app-init:
    depends_on:
    - keycloak
    image: docker.io/dwdraju/alpine-curl-jq:latest
    restart: on-failure
    command:
    - bash
    - -x
    - /etc/horreum/cwd/app-init.sh
    environment:
    - CONTAINER_RUNTIME=podman
    volumes:
    - ./:/etc/horreum/cwd:rw,z
    - horreum_grafana:/etc/grafana
  grafana:
    depends_on:
    - keycloak
    - app-init
    image: grafana/grafana
    entrypoint: /etc/grafana/cwd/grafana.sh
    environment:
    - GF_INSTALL_PLUGINS=simpod-json-datasource
    - GF_SERVER_ROOT_URL=http://localhost:4040/
    - GF_USERS_DEFAULT_THEME=light
    - GF_SECURITY_ALLOW_EMBEDDING=true
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    - GF_AUTH_OAUTH_AUTO_LOGIN=true
    - GF_AUTH_GENERIC_OAUTH_ENABLED=true
    - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana
    - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
    - GF_AUTH_GENERIC_OAUTH_AUTH_URL=http://localhost:8180/auth/realms/horreum/protocol/openid-connect/auth
    - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=http://keycloak:8180/auth/realms/horreum/protocol/openid-connect/token
    - GF_AUTH_GENERIC_OAUTH_API_URL=http://keycloak:8180/auth/realms/horreum/protocol/openid-connect/userinfo
    - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=false
    ports:
    - 4040:3000
    user: "0:0"
    volumes:
    - horreum_grafana:/var/lib/grafana
    - ./:/etc/grafana/cwd/:ro,z
