version: '3.1'
volumes:
  horreum_pg13: {}
services:
  postgres:
    image: docker.io/postgres:13
    env_file: postgres.env
    environment:
      PGPORT: ${POSTGRES_PORT:-5432}
    volumes:
    - horreum_pg13:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  db-init:
    depends_on:
    - postgres
    image: docker.io/postgres:13
    restart: on-failure
    env_file: postgres.env
    environment:
    - PGHOST=172.17.0.1
    - PGPORT=${POSTGRES_PORT:-5432}
    volumes:
    - "${WORKING_PATH:-../}:/cwd:ro,z"
    command:
    - bash
    - -x
    - /cwd/infra/create-db.sh
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    depends_on:
    - postgres
    environment:
      KC_HTTP_HOST: 0.0.0.0
      KC_HTTP_PORT: "${KEYCLOAK_HTTP_PORT:-8180}"
      DB_ADDR: 172.17.0.1
      DB_PORT: "${POSTGRES_PORT:-5432}"
    stop_signal: "${STOP_SIGNAL:-SIGTERM}"
    volumes:
    - "${WORKING_PATH:-../}:/cwd:ro,z"
    ports:
    - "8180:8180"
  app-init:
    depends_on:
    - keycloak
    image: docker.io/dwdraju/alpine-curl-jq
    restart: on-failure
    command:
    - bash
    - -x
    - /cwd/infra/app-init.sh
    - "${PORT_OFFSET:-0}"
    environment:
    - POSTGRES_HOST=localhost
    - KEYCLOAK_HOST=localhost
    volumes:
    - "${WORKING_PATH:-../}:/cwd:rw,z"
  grafana:
    depends_on:
    - keycloak
    - app-init
    image: docker.io/grafana/grafana
    entrypoint: /cwd/infra/grafana.sh
    env_file: grafana.env
    environment:
      GF_SERVER_HTTP_PORT: "${GRAFANA_HTTP_PORT:-4040}"
    stop_signal: "${STOP_SIGNAL:-SIGTERM}"
    user: "0:0"
    volumes:
    - "${WORKING_PATH:-../}:/cwd:ro,z"
    ports:
    - "4040:3000"
