version: '3.1'
volumes:
  horreum_pg12: {}
services:
  postgres:
    image: docker.io/postgres:12
    env_file: postgres.env
    network_mode: host
    environment:
      PGPORT: ${POSTGRES_PORT:-5432}
    volumes:
    - horreum_pg12:/var/lib/postgresql/data
  db-init:
    depends_on:
    - postgres
    image: docker.io/postgres:12
    restart: on-failure
    env_file: postgres.env
    environment:
    # DB-init resolves localhost to ::1 rather than 127.0.0.1
    - PGHOST=127.0.0.1
    - PGPORT=${POSTGRES_PORT:-5432}
    volumes:
    - "${WORKING_PATH:-../}:/cwd:ro,z"
    command:
    - bash
    - -x
    - /cwd/infra/create-db.sh
    network_mode: host
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    depends_on:
    - postgres
    environment:
      KC_HTTP_HOST: localhost
      KC_HTTP_PORT: "${KEYCLOAK_HTTP_PORT:-8180}"
      DB_ADDR: 127.0.0.1
      DB_PORT: "${POSTGRES_PORT:-5432}"
    network_mode: host
    stop_signal: "${STOP_SIGNAL:-SIGTERM}"
    volumes:
    - "${WORKING_PATH:-../}:/cwd:ro,z"
  app-init:
    depends_on:
    - keycloak
    image: docker.io/dwdraju/alpine-curl-jq
    restart: on-failure
    command:
    - bash
    - -x
    - /cwd/infra/app-init.sh
    - "${PORT_OFFSET:-0}"
    environment:
    - POSTGRES_HOST=127.0.0.1
    - KEYCLOAK_HOST=localhost
    network_mode: host
    volumes:
    - "${WORKING_PATH:-../}:/cwd:rw,z"
  grafana:
    depends_on:
    - keycloak
    - app-init
    image: docker.io/grafana/grafana
    entrypoint: /cwd/infra/grafana.sh
    env_file: grafana.env
    environment:
      GF_SERVER_HTTP_PORT: "${GRAFANA_HTTP_PORT:-4040}"
    network_mode: host
    stop_signal: "${STOP_SIGNAL:-SIGTERM}"
    user: "0:0"
    volumes:
    - "${WORKING_PATH:-../}:/cwd:ro,z"
