####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode
###
FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY target/*-runner /work/application
COPY src/main/resources/keycloak-horreum.json /work/imports/
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
