export const CREATE = "schemas/CREATE"
export const DELETE = "schemas/DELETE"
export const UPDATE = "schemas/UPDATE"
export const LOADED = "schemas/LOADED"
export const UPDATE_TOKEN = "schemas/UPDATE_TOKEN"
export const UPDATE_ACCESS = "schemas/UPDATE_ACCESS"
