export const SCHEMA = "tests/SCHEMA"
export const CREATE = "tests/CREATE"
//export const UPDATE = "tests/UPDATE"
export const DELETE = "tests/DELETE"
export const LOADED = "tests/LOADED"
export const UPDATE_TOKEN = "tests/UPDATE_TOKEN"
export const UPDATE_ACCESS= "tests/UPDATE_ACCESS"
