name: Format check - package-lock.json

on:
  pull_request:
    paths:
      - 'horreum-web/package-lock.json'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Prettier
        run: npm install prettier

      - name: Check formatting
        run: |
          if [[ -n "$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- horreum-web/package-lock.json)" ]]; then
            npx prettier --check "horreum-web/package-lock.json"
          fi
