# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      QUAY_BOT_LOGIN: ${{secrets.QUAY_BOT_LOGIN}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml
    - name: Upload artifact for failed workflow
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test logs
        path: |
          */target/surefire-reports/*
          test-suite/target/hyperfoil/*.log
    - name: Get version
      run: echo PROJECT_VERSION=$( mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout ) >> $GITHUB_ENV
    - name: Login to Quay.io
      if: env.QUAY_BOT_LOGIN != '' && github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_BOT_LOGIN }}
        password: ${{ secrets.QUAY_BOT_PASSWORD }}
    - name: Push to Quay.io
      if: env.QUAY_BOT_LOGIN != '' && github.ref == 'refs/heads/master'
      run: docker push quay.io/hyperfoil/horreum:dev
