name: Java CI with Maven

on:
  push:
    branches: [ master ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
      ENVIRONMENT: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Maven Version
      run: mvn --version
    - name: Build with Maven
      run: mvn clean package -B --file pom.xml -DskipTests -Dquarkus.quinoa=false
    - name: Test with Maven
      run: mvn -B verify --file pom.xml -Dquarkus.quinoa=false
    - name: Upload artifact for failed workflow
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test logs
        path: |
          */target/surefire-reports/*
          test-suite/target/hyperfoil/*.log
