name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - 'doc/**'
      - '*.md'
      - '*.txt'
    tags: [ "*" ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - 'doc/**'
      - '*.md'
      - '*.txt'

    workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
        -  {
            name: "windows-latest",
            build-options: "\"-Dquarkus.container-image.build=false\" -pl '!horreum-client, !horreum-integration-tests' -DskipITs -DskipTests"
          }
        - {
            name: "ubuntu-latest",
            build-options: ""
          }
    env:
      ENVIRONMENT: CI
    runs-on:  ${{ matrix.os.name }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 17
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Maven Version
      run: mvn --version
    - name: Build with Maven
      run: mvn clean install -B --file pom.xml -DskipTests -DskipITs ${{ matrix.os.build-options }} -DargLine="-Dci-test=true"
    - name: Test with Maven
      run: mvn -B verify --file pom.xml ${{ matrix.os.build-options }}
    - name: Upload artifact for failed workflow
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test logs
        path: |
          */target/surefire-reports/*
          test-suite/target/hyperfoil/*.log
