name: Node.js GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Node Version
      run: node -v
    - name: Install dependencies
      run: npm install
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Node Version
      run: node -v
    - name: Install dependencies
      run: npm install