name: Upload to quay.io

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    env:
      QUAY_BOT_LOGIN: ${{secrets.QUAY_BOT_LOGIN}}
      ENVIRONMENT: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3 
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Maven Version
      run: mvn --version
    - name: Build with Maven
      run: mvn clean package -B --file pom.xml -DskipTests
    - name: Test with Maven
      run: mvn -B test --file pom.xml
    - name: Upload artifact for failed workflow
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test logs
        path: |
          */target/surefire-reports/*
          test-suite/target/hyperfoil/*.log
    - name: Get version
      run: echo PROJECT_VERSION=$( mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout ) >> $GITHUB_ENV
    - name: Login to Quay.io
      if: env.QUAY_BOT_LOGIN != '' && github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_BOT_LOGIN }}
        password: ${{ secrets.QUAY_BOT_PASSWORD }}
    - name: Push to Quay.io
      if: env.QUAY_BOT_LOGIN != '' && github.ref == 'refs/heads/master'
      run: docker push quay.io/hyperfoil/horreum:dev
