name: Stable branch

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    env:
      ENVIRONMENT: CI
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 0.7.x
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: 21
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Version
        run: mvn --version
      - name: Build with Maven
        run: mvn clean package -B --file pom.xml -DskipTests
      - name: Test with Maven
        run: mvn -B verify --file pom.xml
      - name: Upload artifact for failed workflow
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test logs
          path: |
            */target/surefire-reports/*
            test-suite/target/hyperfoil/*.log
